import { useQuery } from "@tanstack/react-query";
import { useAuth, useUser } from "@clerk/react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getApiUrl } from "@/lib/api";
import { Activity, ArrowUpRight, KeyRound, Landmark, ShieldCheck, UserRound } from "lucide-react";

async function authGet(path, getToken) { const token = await getToken(); const response = await fetch(getApiUrl(path), { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) throw new Error(data?.error || "Request failed"); return data; }
export default function Account() {
  const { getToken } = useAuth();
  const { user } = useUser();
  const { data: account } = useQuery({ queryKey: ["alpaca-account"], queryFn: () => authGet("/api/alpaca/account", getToken), refetchInterval: 30000 });
  const { data: status } = useQuery({ queryKey: ["trading-status"], queryFn: () => authGet("/api/trading/status", getToken), refetchInterval: 30000 });
  return <div className="space-y-6 animate-in fade-in duration-500">
    <div className="border-b border-border/50 pb-4"><div className="flex items-center gap-2 text-primary text-2xl font-bold uppercase tracking-widest"><UserRound size={24} /> Operator profile</div><p className="text-muted-foreground text-sm uppercase tracking-wider mt-1">Identity, execution permissions, and account telemetry.</p></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-2 border-border/50 bg-card/50 backdrop-blur"><CardHeader className="border-b border-border/30"><CardTitle className="text-sm uppercase tracking-widest text-primary">Profile</CardTitle></CardHeader><CardContent className="p-4 space-y-4 text-xs"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center text-primary text-lg">{user?.firstName?.[0] || "G"}</div><div><div className="font-bold">{user?.fullName || "GhostAgent operator"}</div><div className="text-muted-foreground">{user?.primaryEmailAddress?.emailAddress || "Authenticated workspace user"}</div></div><Badge variant="outline" className="ml-auto border-green-500/40 text-green-400">AUTHENTICATED</Badge></div><div className="grid grid-cols-2 gap-3"><Metric label="Paper equity" value={account?.equity ? `$${Number(account.equity).toLocaleString()}` : "—"} /><Metric label="Buying power" value={account?.buyingPower ? `$${Number(account.buyingPower).toLocaleString()}` : "—"} /></div></CardContent></Card><Card className="border-border/50 bg-card/50 backdrop-blur"><CardHeader className="border-b border-border/30"><CardTitle className="text-sm uppercase tracking-widest text-primary flex gap-2 items-center"><Landmark size={15} /> Broker</CardTitle></CardHeader><CardContent className="p-4 space-y-3 text-xs"><Row label="Provider" value="Alpaca" /><Row label="Environment" value={account?.paper ? "PAPER" : "—"} /><Row label="Status" value={account?.status || "—"} /><Row label="Options level" value={account?.optionsTradingLevel || "—"} /><Link href="/alpaca"><Button className="w-full text-[10px] uppercase tracking-wider mt-2">Manage paper account <ArrowUpRight size={12} className="ml-1" /></Button></Link></CardContent></Card></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Info icon={<ShieldCheck />} title="Server-side secrets" text="Credentials are never collected in this interface." /><Info icon={<KeyRound />} title="Order permission" text="Long premium options on paper endpoint only." /><Info icon={<Activity />} title="Risk protocol" text={`${status?.maxRiskPercent || 1}% risk ceiling · ${status?.confidenceGate || 78}% confidence gate`} /></div>
  </div>;
}
function Metric({ label, value }) { return <div className="border border-border/40 p-3"><div className="text-[10px] text-muted-foreground uppercase">{label}</div><div className="font-bold font-mono text-lg mt-1">{value}</div></div>; }
function Row({ label, value }) { return <div className="flex justify-between"><span className="text-muted-foreground">{label}</span><span className="font-bold">{value}</span></div>; }
function Info({ icon, title, text }) { return <div className="border border-border/40 bg-card/30 p-3 flex gap-3"><div className="text-primary">{icon}</div><div><div className="text-xs font-bold uppercase tracking-wider">{title}</div><p className="text-[10px] text-muted-foreground mt-1">{text}</p></div></div>; }