import { pgTable, serial, integer, varchar, decimal, timestamp, text, boolean, jsonb } from "drizzle-orm/pg-core";
import { users } from "./users.js";

export const trades = pgTable("_trading_trades", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  symbol: varchar("symbol", { length: 50 }).notNull(),
  type: varchar("type", { length: 10 }).notNull(),
  entryPrice: decimal("entry_price", { precision: 18, scale: 8 }),
  stopLoss: decimal("stop_loss", { precision: 18, scale: 8 }),
  takeProfit: decimal("take_profit", { precision: 18, scale: 8 }),
  stopLossPips: decimal("stop_loss_pips", { precision: 10, scale: 2 }),
  takeProfitPips: decimal("take_profit_pips", { precision: 10, scale: 2 }),
  riskRewardRatio: varchar("risk_reward_ratio", { length: 20 }),
  recommendedLotSize: decimal("recommended_lot_size", { precision: 10, scale: 4 }),
  riskPercent: decimal("risk_percent", { precision: 5, scale: 2 }),
  accountBalanceAtSignal: decimal("account_balance_at_signal", { precision: 18, scale: 2 }),
  signalStatus: varchar("signal_status", { length: 20 }).notNull().default("active"),
  journalNote: text("journal_note"),
  aiReasoning: text("ai_reasoning"),
  aiConfidence: decimal("ai_confidence", { precision: 5, scale: 2 }),
  forecast: text("forecast"),
  keyLevels: text("key_levels"),
  forecastData: jsonb("forecast_data"),
  shareSettled: boolean("share_settled").notNull().default(false),
  mt5TicketId: varchar("mt5_ticket_id", { length: 100 }),
  timeframe: varchar("timeframe", { length: 10 }),
  session: varchar("session", { length: 50 }),
  confluenceScore: integer("confluence_score"),
  closedAt: timestamp("closed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
